name: Matrix Workflow Example
on:
    workflow_dispatch:
jobs:
    job1:
        strategy:
            matrix:
                os_version: [ubuntu-latest, macos-latest]
                node_version: [16, 18, 20]
            fail-fast: false
            max-parallel: 3
        name: My Jobs using matrix strategy
        runs-on: ${{ matrix.os_version }}
        steps:
            - uses: actions/setup-node@v3.6.0
              with:
                  node-version: ${{ matrix.node_version }}