name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - debug
          - info
          - warning
      tag:
        description: 'Apply tag after successful test run'
        required: true
        type: boolean
      environment:
        description: 'The environment to run test against'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
