on:
    workflow_dispatch

jobs:
  SecretAndVariableExample:
    runs-on: ubuntu-latest

    steps:

      - name: Set secret and var as input
        uses: ActionsInAction/HelloWorld@v1
        with:
            MY_SECRET: ${{ secrets.secret-name }}
            MY_VAR: ${{ vars.variable-name }}
      